export const terms = [
    {
        title: "Terms & Conditions for MCVR",
    },
    {
        title: "Last Updated: 14th January 2024",
    },
    {
        title: "Definitions",
        bullet: "a) ‘Hirer’ means the person or persons nominated as the driver on the Rental Agreement and any person whose debit/credit card is presented in payment of the customer’s charges. b) ‘Rental Period’ means the hire period referred to on the Rental Agreement or any agreed variation thereof and any additional period during which the vehicle is in the customer’s possession or control. c) ‘Vehicle’ means the vehicle as described on the Rental Agreement and includes tires, tools, accessories, any other special equipment, and any replacement or substitute vehicle provided at the discretion of MCVR. d) ‘Driver’ is the person stated as the only driver at the top of the contract, or anybody who appears on the contract further down as an ‘Additional Authorized Driver’. NOBODY ELSE IS PERMITTED TO DRIVE."
    },
    {
        title: "Licenses and Eligibility",
        bullet: "a) Drivers must be between 21 and 70 years of age, in good health, and have a full valid driving license for more than 2 years. Some vehicles have higher minimum/maximum age restrictions. b) Production of a valid, clean driving license is required from all drivers at the start of the rental. Any endorsements/points and or disqualifications, current or pending, must be declared at the time of booking and collection. c) Further identification must be produced, including your National Insurance number (NI Number), a bank or credit card statement, along with a debit/credit card, passport, and/or any other necessary documents to verify identity and address. d) No rental will be undertaken for anybody who has had an 'at fault' accident in the last 12 months or more than one 'at fault' accident thereafter up to the last 3 years, costing the insurer more than £2000 combined for all claims. e) There is only one permitted driver unless agreed by MCVR and listed on the agreement. All additional drivers agree to be bound by the Terms and Conditions of this Agreement. f) Details and presence/signature of additional drivers are required as above. g) The driver must answer truthfully all questions on the insurance proposal incorporated in this agreement. h) The driver must inform MCVR of any changes to their address or circumstances if they are using information from their database given on a previous rental. The same is the case for additional drivers. i) The driver must inform MCVR of any change of address, telephone numbers, or occupation that take place during the rental. j) The driver will not be permitted to rent a vehicle if they have been placed on MCVR's Bad Risk register, and in that case, MCVR may share that information with other rental companies, Police, or other bodies who operate to reduce further risk to the self-drive industry. k) MCVR reserves the right to refuse rental to any person without giving a reason."
    },
    {
        title: "Charges",
        bullet: "a) The Hirer agrees to pay MCVR for all costs and claims that may result from breaking our terms and conditions in any way. aa) All rental charges and security/rental deposit as published by MCVR at the time of rental. b) Any amounts due in respect of any claims resulting from hiring a vehicle from MCVR, including loss or damage to the vehicle and its accessories until the vehicle is checked in by the company during office opening hours. c) The cost of windscreen replacement if it is damaged during the hire. d) Any damage to the vehicle and/or to third party property above 6 feet high (1.83m), including any liabilities incurred. e) Any damage to a Luton box van. f) Any damage caused by an insecure load of any kind or protruding from or strapped to. g) A liability of £7000.00 for any vehicle that is stolen while in the hirer’s possession. h) All other additional charges as they are incurred, including but not limited to, government/local authority seizing or impounding fees and duties, parking and traffic infringement penalties, road toll fines, congestion charges, and associated administration costs. i) Any charges arising from HM Customs & Excise or any local authority seizing or impounding the vehicle, together with a loss of income charge while MCVR cannot rent out the vehicle, plus all recovery costs. j) Any other fees or charges payable by me pursuant to this Agreement. k) A cleaning fee from £50.00 if the vehicle is not returned with a clean interior or an unlimited amount if damaged in any way inside the vehicle. l) Full cost of repairing any vandalism to the vehicle. m) The full cost of restoring the vehicle’s interior and/or exterior due to damage by paint, glue, chemicals, oil, tar, concrete, or similar that is not easily cleaned, however caused during the rental. n) The cost of refilling the tank to the amount of fuel it had when the hire commenced. Plus a 25% refuelling charge. o) The cost of puncture repairs. Replacement of damaged tires, wheels, or undercarriage caused to the vehicle while in the hirer’s custody and control. p) The cost of changing tires if the hirer is unable to do so. q) The hirer authorizes MCVR to charge any credit/debit card used in payment for any part of the contract to pay any further rental and/or charges that fall due under this Agreement. r) There are no refunds for unused fuel, early returns, and late pickups. s) The hirer should not allow the rental vehicle to run out of fuel. In the event, the hirer shall be liable for the full cost of supplying fuel and restarting the vehicle. t) In the event that the hirer allows the wrong fuel to be put into the vehicle fuel tank, there is a minimum charge of £200 to rectify. u) Also see accident reporting penalty under accidents."
    },
    {
        title: "General Use",
        bullet: "a) I acknowledge that the vehicle will not: i) Be used for any illegal purpose. ii) Be used for any kind of rally, race/contest, track days, towing or pushing. iii) Be used for hire or reward of passengers, nor use to carry more passengers than it has seat belts for. iv) Be overloaded with any items that exceed the weight capacity of the vehicle. Any load must be loaded evenly, safely, and with the individual axle loads in mind. v) Be driven with any load overhanging the body. (All loads to be securely attached) vi) Be driven with any load on the roof of the vehicle. No roof racks permitted. vii) Be damaged by submersion or have contact with salt water viii) Be left unattended with keys in the ignition or anywhere else in it. ix) Be driven on roads that have not been sealed with bitumen or concrete. x) Be driven in a manner that was dangerous or may cause damage, but only in a careful and considerate way. xi) Leave the shores of mainland UK without the written permission of MCVR, paying a premium, and having AA 5-star cover or equivalent before leaving. xii) Be driven in a way that would contravene any laws or regulations in any country the vehicle may be used. This includes: not being under the influence of alcohol, drugs, or any other substance that would impair driving ability. xiii) Be used for any purpose that contravenes the Insurance policy, and further undertakes not to use the vehicle after the expiry of the hire agreement unless first paying for and receiving a hire extension form. b) The hirer shall at all times be responsible for the safekeeping of the vehicle. c) In the event that the hirer allows a person to drive the vehicle that is not registered as an additional driver on the Contract, a penalty of £300.00 will be charged. The hire may also be terminated, and no refund of rental charges will be given. d) Any time, grace, or indulgence granted to the hirer by MCVR shall not prejudice the strict rights of MCVR under the terms of the hire agreement. e) Acceptance of the vehicle by the customer confirms acceptance of the Terms and Conditions set out in this Agreement and implies acceptance of the vehicle in good order and sound mechanical condition. f) The vehicle must be returned to the office that the rental started, in the same clean and good mechanical condition as it was at the commencement of the hire. g) The customer is responsible for the proper maintenance of the vehicle during the hire, including checking of oil, water, brake fluid, lights, and tires and reporting any defect immediately to MCVR so that it can be rectified. h) Should failure to maintain the vehicle cause MCVR's policy to be invalid in any way, the customer will bear the cost of any accident or damage that may occur. In the event that mechanical damage occurs due to negligence of the maintenance, hirer will bear the full cost of the repairs to the vehicle."
    },
    {
        title: "General Use (Continued)",
        bullet: "i) MCVR reserves the right to terminate the rental Agreement and take possession of the vehicle without notice and without reason. Any unexpired rental will be refunded, providing this Agreement has not been broken by the hirer. MCVR will not be liable for any loss or delay or any other claim resulting from the repossession. j) The vehicle will remain the absolute property of MCVR at all times. The hirer shall not dispose of, lend, or hire the vehicle or allow any loan or pledge of any kind to be made against it. k) The hirer shall not be permitted to authorize any repairs to the vehicle. MCVR will not be liable to the hirer or any third party for any repairs that have not been authorized in writing. l) In the event that the vehicle is left outside MCVR's premises when closed, it remains the responsibility of the hirer until the next official opening of that office. m) In the event that the hirer fails to return the vehicle to MCVR at the termination of the hire period, the hirer shall be liable for the cost of all inquiries and recovery of the vehicle. n) In the event that the rental exceeds 28 days, the hirer must return and sign a new Rental Agreement. o) For late returns, 25% of the daily charge per hour is charged, unless the next hire is lost, in which case 1 day will be charged. p) The Hirer is liable for the full rental period. No refunds will be made except at the discretion of the owners. In such a case, a minimum of 24 hours' notice must have been given. q) No responsibility of any kind will be taken for items left in the vehicle, whether on normal return or if the vehicle is collected for any reason. Should items of possible value or use be found in the vehicle, we will keep them for 2 weeks before disposing of them. It is the customer's responsibility to ask for and collect any items. If there are outstanding charges, they must be paid before the release of any goods. r) Any verbal or physical aggression towards MCVR officers or staff will not be tolerated and will result in customers being put on bad risk, hire terminated, and Police being called. s) Signing the rental agreement at the time of rental supersedes any terms of supply."
    },
    {
        title: "Accidents",
        bullet: "a) In the event of an accident or incident involving another vehicle or person, the driver will do the following in this order: i) IMMEDIATELY ring the 24-hour Accident Management number given to you on collection of the vehicle and available in the vehicle cab or from MCVR's office during office hours and the emergency line given to the customer on collection. ii) Not make any admission of fault or liability. iii) Take the registration number(s) of the third party vehicle(s) involved, the driver’s name, address, and phone number, and pictures of all the vehicles involved. Also, make sure to check & note the number of occupants/passengers in the Third Party vehicle to avoid fraudulent personal injury claims. iv) Take the name and address and phone number of any witnesses. v) Do anything that the Accident Management staff ask of you. vi) Complete an accident report the same day and submit it to the Accident Management or MCVR's office"
    },
    {
        title: "Furthermore",
        bullet: "g) Failure to ring the Accident Line immediately and speak to an operator will render the customer liable for all costs that develop from any accident or incident. An initial penalty of £300.00 in addition to the excess of the same amount published for that vehicle will be taken whenever we receive notification by anybody of an accident or incident involving MCVR's vehicle outside of the first hour after such happening. h) In the event of an accident that is your fault, any hire charges that have been paid for the period agreed will be lost. No replacement vehicle will be provided. At MCVR's discretion, it will normally refuse to cover any further rental unless the damage is of a minor type, in which case the excess needs to be paid before the hire continues. i) The hirer shall be liable for all recovery costs after an accident, regardless of fault, to MCVR's premises or to their chosen repairer. Providing the third party pays out, these costs can be recovered, providing MCVR has been given the receipts within 14 days of the accident. j) In the event that there is a dispute over any accident or incident, the driver must be helpful to anyone whom MCVR employs to get a settlement. The driver must agree to attend court if the need arises to get a successful conclusion to any claim. Should the driver refuse to cooperate in any way and the claim is lost as a result, the customer will be liable for the full amount of damages, injuries, and costs of both MCVR and the third party(s). k) Should an unreported accident come to light after the deposit has been refunded, MCVR reserves the right to take double the rental deposit, as is your liability, from any payment card(s) used without giving notice. All other conditions will also apply + £300 penalty (see 5g). l) There will be no limit of cost to hirer where an accident or damage has been caused by not driving in accordance with the rules and regulations for road users (i.e., Drink driving, drug use etc.)."
    },
    {
        title: "Own Insurance (Continued)",
        bullet: "a) In the event that the hirer uses their own domestic comprehensive insurance, they must supply a copy of the insurance cover note and details of the broker that arranged it. The broker must be aware that the vehicle belongs to MCVR, and the cover must not cease before the end of the hire. Any excess must be paid by the hirer along with any other liabilities that become due because of any failure of the insurance company to pay out whether for damage or theft. Any damage must be shown to MCVR, and the repairer made known and agreed upon before the repairs are carried out. All repairs must be completed before the return of the vehicle. Hire charges must be paid in advance until the vehicle is returned. b) In the event that the hirer is a company using their company insurance for the rental, a company order and insurance certificate must be supplied stating that the cover is comprehensive and will be used for the full period of rental. Any excess must be paid by the hirer along with any other liabilities that become due because of any failure of the insurance company to pay out whether for damage or theft. Any damage must be shown to MCVR, and the repairer made known and agreed upon before the repairs are carried out. All repairs must be completed before the return of the vehicle. In the case of theft, hire charges apply until settlement for the vehicle is received. c) In the event that the vehicle is returned out of hours, the hirer is responsible for the insurance of that vehicle until the next official opening of our office."
    },
    {
        title: "Vehicle Inspection",
        bullet: " a) The hirer acknowledges that the vehicle will undergo a thorough inspection before the commencement of the rental period. Any pre-existing damage or issues will be documented in the rental agreement. b) The hirer agrees to return the vehicle in the same condition, allowing for reasonable wear and tear, as it was at the commencement of the hire. c) Any new damage discovered upon return will be assessed, and the hirer will be responsible for the repair costs. MCVR reserves the right to charge the hirer's credit/debit card for these costs."
    },
    {
        title: "Payment and Charges",
        bullet: "a) The hirer agrees to pay all rental charges and security/rental deposit as published by MCVR at the time of rental. b) The hirer is responsible for any amounts due in respect of claims resulting from hiring a vehicle from MCVR, including loss or damage to the vehicle and its accessories until the vehicle is checked in by the company during office opening hours. c) The hirer is liable for any damage to the vehicle and/or third-party property above 6 feet high (1.83m), including any liabilities incurred. d) The hirer is responsible for any damage to a Luton box van. e) The hirer agrees to a liability of £7000.00 for any vehicle stolen while in the hirer’s possession. f) The hirer agrees to pay for any costs and claims resulting from breaking the terms and conditions in any way. g) The hirer acknowledges and agrees to pay the cost of windscreen replacement if it is damaged during the hire. h) The hirer agrees to pay for any damage caused by an insecure load of any kind or protruding from or strapped to the vehicle. i) The hirer accepts a liability of £50.00 for any vehicle returned without a clean interior. j) The hirer agrees to pay the full cost of repairing any vandalism to the vehicle. k) The hirer accepts the full cost of restoring the vehicle’s interior and/or exterior due to damage by paint, glue, chemicals, oil, tar, concrete, or similar that is not easily cleaned, however caused during the rental. l) The hirer is responsible for the cost of refilling the tank to the amount of fuel it had when the hire commenced, plus a 25% refueling charge. m) The hirer agrees to pay for any puncture repairs, replacement of damaged tires, wheels, or undercarriage caused to the vehicle while in the hirer’s custody and control. n) The hirer acknowledges that there are no refunds for unused fuel, early returns, and late pickups."
    },
    {
        title: "Privacy Policy",
        bullet: "a) MCVR is committed to protecting the privacy of its customers. The full privacy policy is available on the website and outlines how personal information is collected, used, and stored."
    },


]
export const privacy = {
    title: "Privacy Policy for MCVR Ltd. T/a Malgam Car and Van Rental",
    lastUpdated: "Last Updated: 14th January 2024",
    subheading: "At MCVR, we are committed to protecting the privacy of our customers. This Privacy Policy outlines how we collect, use, disclose, and manage your personal information when you interact with our website, services, and rental offerings. By using MCVR services, you agree to the terms outlined in this policy.",
    terms: [
        {
            title: "Information We Collect",
            paragraph: "We collect personal information provided by you during the reservation and rental process. This may include, but is not limited to, your name, contact details, driver's license information, payment details, and other relevant data necessary for the rental transaction."
        },
        {
            title: "How We Use Your Information",
            paragraph: "The personal information collected is used for the purpose of facilitating your rental, processing payments, and providing customer support. Additionally, we may use your contact information to send you updates, promotional materials, or important notices related to your rental or changes in our services."
        },
        {
            title: "Data Security",
            paragraph: "We take reasonable steps to ensure the security of your personal information. This includes implementing appropriate technical and organisational measures to prevent unauthorised access, disclosure, alteration, or destruction of your data."
        },
        {
            title: "Information Sharing",
            paragraph: "We may share your personal information with third-party service providers, such as payment processors and insurance companies, to facilitate the rental process. We do not sell or lease your personal information to third parties for their marketing purposes."
        },
        {
            title: "Cookies and Tracking Technologies",
            paragraph: "Our website may use cookies and other tracking technologies to enhance your browsing experience. You can manage your cookie preferences through your browser settings."
        },
        {
            title: "Your Choices",
            paragraph: "You have the right to access, update, or request the deletion of your personal information. To do so, please contact us at [your contact email/phone number]."
        },
        {
            title: "Changes to Privacy Policy",
            paragraph: "We may update this Privacy Policy periodically. The latest version will be posted on our website with the effective date. Your continued use of our services after any modifications constitutes your acceptance of the updated policy."
        },
        {
            title: "Contact Us",
            paragraph: "If you have any questions, concerns, or requests regarding this Privacy Policy, please contact us at [your contact email/phone number]. <br/> Thank you for trusting MCVR with your rental needs.Your privacy is important to us, and we are committed to maintaining the confidentiality and security of your personal information."
        },
    ]
}